server:
  port: 8090

spring.jpa:
  database: POSTGRESQL
  hibernate.ddl-auto: update
  show-sql: true
  generate-ddl: true

spring:
  kafka:
    :bootstrap-servers: ${KAFKA_BROKER:localhost:9092}
    topic:
      orchestrator: orchestrator
      product-validation-success: product-validation-success
      product-validation-fail: product-validation-fail
    consumer:
      group-id: product-validation-group



spring.datasource:
  platform: postgres
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://database-1.claei0us2ulm.us-east-2.rds.amazonaws.com/postgres
  username: postgres
  password: 
